backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\components\Controller;
use common\models\User;
use common\models\UserSearch;
use yii\web\NotFoundHttpException;
use Yii;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setScenario('administrator');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use common\models\LoginForm;
use common\models\User;
use common\models\UserStation;
use yii\filters\AccessControl;
use Yii;
use yii\helpers\Url;

/**
 * User controller
 */
class UserController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'set-email', 'buy-pro','reset-password', 'request-password-reset', 'referral', 'signup','captcha'],
                'rules' => [
                    [
                        'actions' => ['signup', 'request-password-reset', 'reset-password', 'referral','captcha'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'set-email', 'buy-pro','reset-password', 'request-password-reset', 'referral'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Авторизация
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout= '/login';
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Регистрация
     * @return string|\yii\web\Response
     */
    public function actionSignup()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $oUserStation = new UserStation();
        $oModel = new User();
        $this->layout= '/login';

        $user_referral = Yii::$app->session['id'];

        $oModel->setScenario('signup');
        if ( $oModel->load($_POST) && $oModel->signup() ) {

            if (Yii::$app->getUser()->login($oModel)){

                if($user_referral){
                    $oModel->setScenario('referrals');
                    $oModel->referrals = $user_referral;
                    $oModel->save();
                }

                $oUserStation->user_id = $oModel::u()->id;
                $oUserStation->stantion_id = 1;
                $oUserStation->count_stations_purchased = 1;
                $oUserStation->save();

                return $this->redirect(['page/index']);
            }
        }
        return $this->render('signup', compact('oModel'));
    }
    public function actionReferral($id){
        Yii::$app->session['id'] = $id;
        $this->redirect('signup');
    }

    /**
     * Выход
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }



    /**
     * Восстановление пароля
     * @return string|\yii\web\Response
     */
    public function actionRequestPasswordReset()
    {
        $model = new User();
        $model->setScenario('requestPasswordResetToken');

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendResetPasswordRequestEmail()) {
                Yii::$app->getSession()->setFlash('success', \Yii::t('app','Проверьте свою электронную почту для получения дальнейших инструкций.'));

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', \Yii::t('app','К сожалению, вы не можете сбросить пароль для данной электронной почты.'));
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Сброс пароля
     * @param $token
     *
     * @return string|\yii\web\Response
     * @throws \yii\web\BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $model = new User();

        $model->setScenario('resetPassword');

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if( $model->save() ){
                Yii::$app->getSession()->setFlash('success', \Yii::t('app','Пароль успешно сохранен'));

                return $this->goHome();
            }else
                Yii::$app->getSession()->setFlash('error', \Yii::t('app','Не удалось сохранить пароль.'));
        }


        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionChangePassword()
    {
        $model =  User::u();
        $model->setScenario('changePassword');

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $data = Yii::$app->request->post('User');
            if ($model->validatePassword($data['oldPassword'])){
                if ($data['password'] === $data['passwordRepeat']){
                    $model->password = $data['password'];
                    $model->setPassword($data['password']);
                    if ($model->save()){
                        Yii::$app->session->setFlash('success', \Yii::t('app','Пароль изменен.'));
                        return $this->render('change_password', ['model' => $model]);
                    } else {
                        Yii::$app->session->setFlash('error', \Yii::t('app','Ошибка! Обратитесь к администратору.'));
                    }
                } else {

                    Yii::$app->session->setFlash('error', \Yii::t('app','Палоли не совпадают.'));
                }
            } else {
                Yii::$app->session->setFlash('error', \Yii::t('app','Старый пароль введен не верно.'));
            }
        }
        return $this->render('change_password', [
            'model' => $model,
        ]);
    }
}

frontend/views/user/change_password.php
<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 01.10.2014
 * Time: 15:32
 */
use frontend\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Смена пароля';
?>
<style>
    .control-label{
        color: #000000 !important;
        margin-left: 5px;
        padding-top: 10px;
    }
</style>
<div class="site-about">
    <p style="padding: 20px"> Пароль должен состоять из 6-20 символов, допустимы только англ. символы.<br /></p>
    <?= Alert::widget();?>
    <div  style="width: 400px; margin-left: auto; margin-right: auto">
        <?php $form = ActiveForm::begin(['id' => 'change-form']); ?>
        <div>
            <?= $form->field($model, 'oldPassword')->passwordInput(['class'=>'form-input-pass'])?>
        </div>
        <div >
            <?= $form->field($model, 'password')->passwordInput(['class'=>'form-input-pass'])?>
        </div>
        <div >
            <?= $form->field($model, 'passwordRepeat')->passwordInput(['class'=>'form-input-pass'])?>
        </div>
        <div class="center" style="margin-left: 90px">
            <?= Html::submitButton(\Yii::t('app','Изменить пароль'), ['class' => 'btn btn-primary btn-lg'])?>
        </div>
        <?php ActiveForm::end(); ?>
        <br />
    </div>
</div>

frontend/views/user/login.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var \common\models\LoginForm $model
 */
$this->title = \Yii::t('app','Вход');
?>
<section class="intro">
    <div class="introContent">
        <div id="holder" class="container">
            <div id="intro_form" class="row">
                <div class="col-xs-2 col-sm-2 col-md-5 col-lg-7"></div>

                <div id="form_login" class="col-xs-10 col-sm-10 col-md-7 col-lg-5 form_register">
                    <h4><?=\Yii::t('app','Войти')?></h4>

                    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                    <div id="input_email" class="col-md-12">
                        <?= $form->field($model, 'email')->textInput(['placeholder' => 'E-mail']) ?>
                    </div>
                    <div id="input_password" class="col-md-12" style=" height: 90px;">
                        <?= $form->field($model, 'password')->passwordInput(['placeholder' => \Yii::t('app','Пароль')]) ?>
                        <?= $form->field($model, 'rememberMe')->checkbox( );  \Yii::t('app','Утеряли доступы?')?>
                        <div class ="dos" style="color:#999; float: right; height: 40px; display: inline; margin-top: -35px;">
                            <?=\Yii::t('app','Утеряли доступы?')?> <?= Html::a(\Yii::t('app', 'Восстановить!'), ['user/request-password-reset'], array('style'=>'color:#fff')) ?>
                        </div>
                    </div>

                    <div id="form_register_btn" class="text-center">
                        <?= Html::submitButton(\Yii::t('app','Войти'), ['class' => 'btn btn-primary btn-lg', 'name' => 'login-button']) ?>
                    </div>
                    <?php ActiveForm::end(); ?>


                    <div class="clearfix"></div>
<!--                    <div class="sign-in-bar">-->
<!--                        <p>--><?//=\Yii::t('app','Нет аккаунта? ')?><!--<a href="/user/signup"><i class="fa fa-lock"></i>--><?//=\Yii::t('app','РЕГИСТРАЦИЯ')?><!--</a> </p>-->
<!--                    </div>-->
<!--                    <div class="sign-in-terms">-->
<!--                        <p>--><?//=\Yii::t('app','Ваши контактные данные не будут переданы третьим лицам')?><!--</p>-->
<!--                            <p>--><?//=\Yii::t('app','Нажав кнопку "Зарегистрироваться", Вы принимаете наши')?><!-- <a href="#" target="_blank">-->
<!--                                    --><?//=\Yii::t('app','Условия соглашения')?><!--</a> и <a href="#" target="_blank">--><?//=\Yii::t('app','Политику конфиденциальности')?><!--</a></p>-->
<!---->
<!--                    </div>-->
                </div>


            </div><!--end_intro_form-->

        </div>
    </div>
</section>

frontend/views/user/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var \frontend\models\PasswordResetRequestForm $model
 */
$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset" style="text-align: center; width: 500px; margin: 0 auto;">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?=\Yii::t('app', 'Пожалуйста, заполните электронную почту.Ссылка для сброса пароля будет отправлена ​​вам.')?></p>

    <?= \frontend\widgets\Alert::widget(); ?>

            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
</div>

frontend/views/user/resetPassword.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var \frontend\models\ResetPasswordForm $model
 */
$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?=\Yii::t('app', 'Пожалуйста, выберите ваш новый пароль:')?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/user/signup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;


/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var \frontend\models\SignupForm $oModel
 */
$this->title = 'Регистрация';
?>
<section class="intro">
    <div class="introContent">
        <div id="holder" class="container">
            <div id="intro_form" class="row">
                <div class="col-xs-2 col-sm-2 col-md-5 col-lg-7"></div>

                <!--Регистрация-->
                <div id="form_register" class="col-xs-10 col-sm-10 col-md-7 col-lg-5 form_register" style="display: block;">
                    <h4><?=\Yii::t('app','Начни уже сейчас')?></h4>

                    <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                    <div id="input_name" class="col-md-12">
                        <?= $form->field($oModel, 'username')->textInput(array('placeholder' =>  \Yii::t('app','Имя')))  ?>
                    </div>
                    <div id="input_email" class="col-md-12">
                        <?= $form->field($oModel, 'email')->textInput(array('placeholder' => 'E-mail'))  ?>
                    </div>
                    <div id="input_password" class="col-md-12">
                        <?= $form->field($oModel, 'password')->passwordInput(array('placeholder' => \Yii::t('app','Пароль')))  ?>
                    </div>
                    <div id="input_capcha" class="col-md-12">
                        <?= $form->field($oModel, 'captcha')->widget(\yii\captcha\Captcha::className()) ?>
                    </div>
                    <div id="input_capcha" class="col-md-12">
                        <div style="color: #fff; float: left;margin-top: 2px;">С <a href="<?= \yii\helpers\Url::to(['page/rules']) ?>" style="color: #fff">правилами</a>  проекта ознакомлен(а) и принимаю:</div><?= $form->field($oModel, 'check')->checkbox() ?>
                    </div>


                    <div id="form_register_btn" class="text-center">
                        <?= Html::submitButton(\Yii::t('app','Регистрация'), ['class' => 'btn btn-primary btn-lg', 'name' => 'signup-button']) ?>
                    </div>
                    <?php ActiveForm::end(); ?>


                    <div class="clearfix"></div>
<!--                    <div class="sign-in-bar">-->
<!--                        <p>--><?//=\Yii::t('app','Войти с ')?><!--<a href="/user/login"><i class="fa fa-unlock"></i>--><?//=\Yii::t('app','СУЩЕСТВУЮЩИМ АККАУНТОМ')?><!--</a> </p>-->
<!--                    </div>-->
<!--                    <div class="sign-in-terms">-->
<!--                        <p>--><?//=\Yii::t('app','Ваши контактные данные не будут переданы третьим лицам')?><!--</p>-->
<!--                        <p>--><?//=\Yii::t('app','Нажав кнопку "Зарегистрироваться", Вы принимаете наши')?><!-- <a href="#" target="_blank">-->
<!--                                --><?//=\Yii::t('app','Условия соглашения')?><!--</a> и <a href="#" target="_blank">--><?//=\Yii::t('app','Политику конфиденциальности')?><!--</a></p>-->
<!--                    </div>-->
                </div>

            </div><!--end_intro_form-->
        </div>
    </div>
</section>